##############################################################################
## Provision nginx-oss-apb
## This role executes much of the needed functionality to provision an
## application using an Ansible Playbook Bundle.  Included in the comments
## below are some sample resources for getting started deploying an application
## to OpenShift.
##############################################################################

##############################################################################
## An OpenShift Origin deployment configuration provides a replication
## controller, spins up pods, and also provides the ability to transition from
## one deployment of an image to a new one.
## https://docs.openshift.org/latest/architecture/core_concepts/deployments.html#deployments-and-deployment-configurations
##############################################################################
- name: create nginx-oss-apb deployment config
  openshift_v1_deployment_config:
    name: nginx-oss-apb
    namespace: '{{ namespace }}'
    state: present
    labels:
      app: '{{ namespace }}'
      service: nginx-oss-apb
    replicas: 1
    selector:
      app: '{{ namespace }}'
      service: nginx-oss-apb
    spec_template_metadata_labels:
      app: '{{ namespace }}'
      service: nginx-oss-apb
    containers:
    - env:
      image: docker.io/library/nginx # replace with your application image
      name: nginx-oss-apb
      ports:
      - container_port: 80
        protocol: TCP
    restart_policy: Always


##############################################################################
## A Kubernetes service serves as an internal load balancer.  It identifies a
## set of replicated pods in order to proxy the connections it receives to them.
## https://docs.openshift.org/latest/architecture/core_concepts/pods_and_services.html#services
##############################################################################
- name: create nginx-oss-apb service
  k8s_v1_service:
    name: nginx-oss-apb
    namespace: '{{ namespace }}'
    state: present
    selector:
      app: '{{ namespace }}'
    ports:
      - name: web
        port: 80
        target_port: 80


##############################################################################
## An OpenShift Origin route exposes a service at a host name, so that external
## clients can reach it by name. Each route consists of a name, a service
## selector, and an optional security configuration.
## https://docs.openshift.org/latest/architecture/core_concepts/routes.html
##############################################################################
- name: create nginx-oss-apb route
  openshift_v1_route:
    name: nginx-oss-apb
    namespace: '{{ namespace }}'
    spec_port_target_port: web
    labels:
      app: '{{ namespace }}'
      service: nginx-oss-apb
    to_name: nginx-oss-apb
